export const brandsProduct = {
  2: [
    { id: "nike", name: "برند نایک" },
    { id: "joma", name: "برند جوما" },
    { id: "mizuno", name: "برند میزانو" },
    { id: "puma", name: "برند پوما" },
    { id: "adidas", name: "برند آدیداس" },
    { id: "asics", name: "برند اسیکس" },
    { id: "local ", name: "برند داخلی" },
    { id: "kelme", name: "برند کلمه" },
  ],
  3: [
    { id: "adidas", name: "برند آدیداس" },
    { id: "newbalance", name: "برند نیوبالانس" },
    { id: "joma", name: "برند جوما" },
    { id: "nike", name: "برند نایک" },
    { id: "local ", name: "برند داخلی" },
  ],
  4: [
    { id: "nike", name: "برند نایک" },
    { id: "joma", name: "برند جوما" },
    { id: "adidas", name: "برند آدیداس" },
  ],
  6: [
    { id: "majid", name: "برند مجید" },
    { id: "local ", name: "برند داخلی" },
    { id: "adidas", name: "برند آدیداس" },
    { id: "fox", name: "برند فوکس" },
    { id: "uhlsport", name: "برند الشپرت" },
  ],
  7: [{ id: "local ", name: "برند داخلی" }],
  8: [
    { id: "asics", name: "برند اسیکس" },
    { id: "umbro", name: "برند آمبرو" },
  ],
  9: [
    { id: "joma", name: "برند جوما" },
    { id: "uhlsport", name: "برند الشپرت" },
    { id: "adidas", name: "برند آدیداس" },
    { id: "nike", name: "برند نایک" },
  ],
  10: [{ id: "uhlsport", name: "برند الشپرت" }],
};

export const brands = [
  { id: 1, Name: "ASICS" },
  { id: 2, Name: "adidas" },
  { id: 3, Name: "ATHLETA" },
  { id: 4, Name: "joma" },
  { id: 5, Name: "kelme" },
  { id: 6, Name: "mizuno" },
  { id: 7, Name: "New Balance" },
  { id: 8, Name: "nike" },
  { id: 9, Name: "puma" },
  { id: 10, Name: "REEBOK" },
  { id: 11, Name: "SENDA" },
  { id: 12, Name: "umbro" },
  { id: 13, Name: "x munich" },
];
export const upperMaterials = [
  { id: 1, Name: "TPU" },
  { id: 2, Name: "الیاف مصنوعی" },
  { id: 3, Name: "بافت فشرده" },
  { id: 4, Name: "بافت فشرده و TPU" },
  { id: 5, Name: "پارچه" },
  { id: 6, Name: "چرم جیر" },
  { id: 7, Name: "چرم طبیعی" },
  { id: 8, Name: "چرم طبیعی کانگورو" },
  { id: 9, Name: "چرم مصنوعی" },
  { id: 10, Name: "رابر" },
  { id: 11, Name: "سیلیکون" },
  { id: 12, Name: "مش" },
  { id: 13, Name: "مواد نساجی" },
  { id: 14, Name: "نایلون" },
  { id: 15, Name: "کتان" },
];
export const collections = [
  { id: 1, Name: "Dribling" },
  { id: 2, Name: "FS REACTIVE" },
  { id: 3, Name: "Invicto" },
  { id: 4, Name: "MAXIMA" },
  { id: 5, Name: "Calcetto" },
  { id: 6, Name: "CANCHA" },
  { id: 7, Name: "Gato" },
  { id: 8, Name: "King" },
  { id: 9, Name: "LIGA 5" },
  { id: 10, Name: "Mercurial" },
  { id: 11, Name: "MUNDIAL" },
  { id: 12, Name: "Pegasus" },
  { id: 13, Name: "Phantom" },
  { id: 14, Name: "Prisma" },
  { id: 15, Name: "Regate" },
  { id: 16, Name: "TACTICO" },
  { id: 17, Name: "Tango" },
  { id: 18, Name: "Tiempo" },
  { id: 19, Name: "Top Flex" },
  { id: 20, Name: "Vapor" },
  { id: 21, Name: "Winflo" },
  { id: 22, Name: "Zoom" },
];
