// /api/products.js
export default function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*"); // اجازه همه دامنه‌ها
  res.setHeader("Access-Control-Allow-Methods", "GET"); // مجاز به این متدها
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");
  if (req.method === "OPTIONS") {
    res.status(200).end();
    return;
  }
  if (req.method === "GET") {
    const id = req.query.id;
    const category = req.query.category_id;
    const brand = req.query.brand;
    const products = [
      {
        id: "1",
        category_id: 2,
        name: "کفش فوتسال نایک ری اکت گتو NIKE REACT GATO IC CT0550-500",
        model: "NIKE REACT GATO IC CT0550-500",
        brand: "نایک",
        sales: 500,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        color: ["بنفش"],
        sizes: ["40.5", "42", "42.5"],
        price: 8400000,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/416313585.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/5511126302.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/5511126303.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/7593908654.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/7593908655.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس سیلیکون و مواد مصنوعی",
          "وزن سبک",
          "قدرت تهویه هوای مناسب",
          " دارای فناوری NIKESKIN جهت کنترل بهتر توپ",
          "زیره دارای فناوری جهت چرخش مناسب هنگام ضربات",
          " زیره دارای فناوری NIKE REACT جهت کاهش فشار وارده از زمین به کفش",
        ],
        technical_details: {
          articleNum: "CT0550-500",
          brand: "nike",
          upper_material: "سیلیکون",
          outsole: "react",
          Collection: "gato",
          quality: "اورجینال(درجه1)",
          warranty: "گارانتی 150 درصدی اصالت کالا و تعویض سایز",
        },
      },
      {
        id: "2",
        category_id: 2,
        name: "کفش فوتسال نایک لونارگتو 2 NIKE LUNAR GATO II IC 580456-570",
        model: "NIKE LUNAR GATO II IC 580456-570",
        brand: "نایک",
        sales: 200,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        color: ["بنفش"],
        sizes: ["40", "41", "42.5", "44"],
        price: 8197200,
        discount: {
          type: "dynamic",
          discountedPrice: 7220000,
          spetial: true,
          startDate: "2025-04-25",
          endDate: "2025-07-1",
        },
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/558855856.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/1045955451.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/1045955452.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/1363526783.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/1363526784.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/9704290195.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس چرم طبیعی",
          "وزن سبک",
          "مناسب برای بازیکنان تکنیکی و سرعتی",
          "دارای زیره نرم با انعطاف پذیری بالا",
          "چسبندگی بالای زیره",
        ],
        technical_details: {
          articleNum: "580456-570",
          brand: "nike",
          upper_material: "چرم طبیعی",
          Collection: "tiempo",
          quality: "اورجینال(درجه1)",
          warranty: "گارانتی 150 درصدی اصالت کالا و تعویض سایز",
        },
      },
      {
        id: "3",
        category_id: 2,
        name: "کفش فوتسال نایک لونارگتو NIKE LUNAR GATO II 580456-105",
        model: "NIKE LUNAR GATO II 580456-105",
        brand: "نایک",
        sales: 200,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        color: ["سفید"],
        sizes: ["40", "40.5", "41", "42", "44", "44.5", "45"],
        price: 8800000,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/227864957.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/580700801.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/9610733502.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/9610733503.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/9610733504.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/509672895.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس چرم طبیعی",
          "وزن سبک",
          "کیفیت دوخت عالی",
          " افزایش قدرت و دقت ضربات با نوک پا",
          " دارای فناوری لونارلون جهت پخش انرژی وارده از زمین به کفش",
          "دارای زیره ضد سایش",
        ],
        technical_details: {
          articleNum: "580456-105",
          brand: "nike",
          upper_material: "چرم طبیعی",
          outsole: "lunarlon",
          Collection: "gato",
          quality: "اورجینال(درجه1)",
          warranty: "گارانتی 150 درصدی اصالت کالا و تعویض سایز",
        },
      },
      {
        id: "4",
        category_id: 2,
        name: "کفش فوتسال نایک کفش فوتسال نایک تمپو لجند 9 آکادمی NIKE TIEMPO LEGEND 9 ACADEMY IC DA1190-007",
        model: "NIKE TIEMPO LEGEND 9 ACADEMY IC DA1190-007",
        brand: "نایک",
        sales: 200,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        color: ["مشکی"],
        sizes: ["44.5", "45"],
        price: 6450000,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/80696246.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/9188364871.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/9188364872.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/4194888723.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/4194888724.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/4194888725.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس چرم طبیعی گوساله",
          "وزن سبک تر نسبت به نسخه های قبلی",
          "انعطاف‌پذیری منحصر به فرد",
          " توانایی کنترل بالای توپ",
          "افزایش قدرت و دقت ضربات با نوک پا و بغل پا",
          "زیره میانی از جنس فوم",
          "فیت شوندگی مناسب",
          "زیره نرم و راحت",
        ],
        technical_details: {
          articleNum: "DA1190-007",
          brand: "nike",
          upper_material: "چرم طبیعی",
          Collection: "tiempo",
          quality: "اورجینال(درجه1)",
          warranty: "گارانتی 150 درصدی اصالت کالا و تعویض سایز",
        },
      },
      {
        id: "5",
        category_id: 2,
        name: "کفش فوتسال نایک ری اکت گتو NIKE REACT GATO IC CT0550-343",
        model: "NIKE REACT GATO IC CT0550-343",
        brand: "نایک",
        sales: 200,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        color: ["سبز"],
        sizes: ["42.5", "44", "44.5", "46"],
        price: 9066600,
        discount: {
          type: "dynamic",
          discountedPrice: 7884000,
          spetial: true,
          startDate: "2025-04-25",
          endDate: "2025-07-1",
        },
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/816236283.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/2352975991.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/1773534762.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/1773534763.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/903409504.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/903409505.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          " رویه دارای فناوری FLYKNIT جهت افزایش نقاط درگیری توپ با کفش",
          "رویه از جنس سیلیکون که هم دوام بالایی دارد و هم توانایی کنترل توپ را بالا می برد",
          "زیره دارای فناوری TOUCH360 جهت تسهیل در چرخش هنگام ضربات",
          " زیره دارای فناوری REACT جهت کاهش فشار وارده از زمین به کفش",
        ],
        technical_details: {
          articleNum: "DA1183-075",
          brand: "nike",
          upper_material: "بافت فشرده",
          outsole: "react",
          Collection: "gato",
          quality: "اورجینال(درجه1)",
          warranty: "گارانتی 150 درصدی اصالت کالا و تعویض سایز",
        },
      },
      {
        id: "6",
        category_id: 2,
        name: "کفش فوتسال نایک ری اکت ایک تمپو لجند 10 آکادمی TIEMPO LEGEND 10 ACADEMY IC DV4341_100",
        model: "TIEMPO LEGEND 10 ACADEMY IC DV4341_100",
        brand: "نایک",
        sales: 200,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        color: ["سفید"],
        sizes: ["44", "44.5", "45", "46"],
        price: 7500000,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/392563925.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/9596775651.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/5562145912.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/5562145913.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/5562145914.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/5562145915.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "کیفیت دوخت ایده آل",
          "وزن سبک",
          "دوام و ماندگاری بالا",
          "زیره نرم و انعطاف پذیر",
        ],
        technical_details: {
          articleNum: "DV4341_100",
          brand: "nike",
          upper_material: "چرم مصنوعی",
          Collection: "tiempo",
          quality: "اورجینال(درجه1)",
          warranty: "گارانتی 150 درصدی اصالت کالا و تعویض سایز",
        },
      },
      {
        id: "7",
        category_id: 2,
        name: "کفش فوتسال نایک لونارگتو 2 NIKE LUNAR GATO II IC 580456-800",
        model: "NIKE LUNAR GATO II IC 580456-800",
        brand: "نایک",
        sales: 200,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        color: ["نارنجی"],
        sizes: ["42.5", "43", "44", "44.5"],
        price: 8100000,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/699826987.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/3311864442.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/7217486031.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/5562145913.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/3311864443.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/9298341575.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس چرم طبیعی",
          "وزن سبک",
          "افزایش قابلیت ضربات با نوک پا",
          "کیفیت دوخت مناسب",
          "دارای زیره ضد سایش",
          "زیره دارای فناوری لونارلون جهت نرمی و کاهش خستگی پاها",
        ],
        technical_details: {
          articleNum: "580456-800",
          brand: "nike",
          upper_material: "چرم طبیعی",
          outsole: "lunarlon",
          Collection: "gato",
          quality: "اورجینال(درجه1)",
          warranty: "گارانتی 150 درصدی اصالت کالا و تعویض سایز",
        },
      },
      {
        id: "8",
        category_id: 2,
        name: "نایک لونارگتو NIKE LUNAR GATO II IC 580456-011",
        model: "NIKE LUNAR GATO II IC 580456-011",
        brand: "نایک",
        sales: 200,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        color: ["سفید"],
        sizes: ["38.5", "40.5", "42", "44.5", "45", "46"],
        price: 8800000,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/703201680.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/4493108901.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/9378683802.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/8325775783.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/8325775784.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/4341067055.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس چرم طبیعی",
          "وزن سبک",
          "مناسب برای بازیکنان تکنیکی و سرعتی",
          "افزایش قابلیت ضربات با نوک پا",
          "زیره دارای فناوری لونارلون جهت نرمی و کاهش خستگی پاها",
        ],
        technical_details: {
          articleNum: "580456-011",
          brand: "nike",
          upper_material: "چرم طبیعی",
          outsole: "lunarlon",
          Collection: "gato",
          quality: "اورجینال(درجه1)",
          warranty: "گارانتی 150 درصدی اصالت کالا و تعویض سایز",
        },
      },
      {
        id: "9",
        category_id: 2,
        name: "نایک کفش فوتسال جوما تاپ فلکس JOMA TOPFLEX 2404 ROYAL",
        model: "JOMA TOPFLEX 2404 ROYAL",
        brand: "جوما",
        sales: 200,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        color: ["آبی"],
        sizes: ["43"],
        price: 6220000,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/47649205.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/6898636181.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/2864006442.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/2864006443.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/9726389244.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/9726389245.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس چرم طبیعی",
          "کیفیت دوخت داخلی و بیرونی عالی",
          "مناسب برای بازیکنان تکنیکی و سرعتی",
          "کفی ساخته شده از مواد ایوا جهت افزایش نرمی وفیت شوندگی",
          "زیره دارای انعطاف پذیری منحصر به فرد",
          "دارای زیره ضد سایش",
        ],
        technical_details: {
          articleNum: "JOMA TOP FLEX 2404 ROYAL",
          brand: "joma",
          upper_material: "چرم طبیعی",
          Collection: "top flex",
          warranty: "گارانتی 150 درصدی اصالت کالا و تعویض سایز",
        },
      },
      {
        id: "10",
        category_id: 2,
        name: "کفش فوتسال جوما تاپ فلکس ریباند JOMA TOP FLEX REBOUND 2401 BLACK GREEN",
        model: "JOMA TOP FLEX REBOUND 2401 BLACK GREEN",
        brand: "جوما",
        sales: 200,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        color: ["مشکی"],
        sizes: ["40.5", "41", "42.5", "43", "45"],
        price: 7290000,
        discount: {
          type: "dynamic",
          discountedPrice: 6800000,
          startDate: "2025-04-25",
          endDate: "2025-07-1",
        },
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/933359518.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/5601122341.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/6521168612.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/2839408743.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس چرم طبیعی",
          "کیفیت دوخت داخلی و بیرونی عالی",
          "توانایی کنترل بالای توپ",
          "دارای فوم در قسمت میانی زیره جهت افزایش نرمی",
          "دارای فناوری ریباند در قسمت زیره جهت کاهش فشار وارده از زمین به کفش",
          "دارای زیره ضد سایش",
        ],
        technical_details: {
          articleNum: "joma top flex 2401 black green",
          brand: "joma",
          upper_material: "چرم طبیعی",
          outsole: "rebound",
          Collection: "top flex",
          warranty: "گارانتی 150 درصدی اصالت کالا و تعویض سایز",
        },
      },
      {
        id: "11",
        category_id: 2,
        name: "کفش فوتسال جوما تاپ فلکس ریباند JOMA TOP FLEX REBOUND 2403 NAVY RED",
        model: "JOMA TOP FLEX REBOUND 2403 NAVY RED",
        brand: "جوما",
        sales: 200,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        color: ["مشکی"],
        sizes: ["45"],
        price: 6750000,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/54679921.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/7582330761.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/6683391392.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/6683391393.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/6683391394.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/5701511285.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس چرم طبیعی",
          "کیفیت دوخت داخلی و بیرونی عالی",
          "توانایی کنترل بالای توپ",
          "دارای فوم در قسمت میانی زیره جهت افزایش نرمی",
          "دارای فناوری ریباند در قسمت زیره جهت کاهش فشار وارده از زمین به کفش",
          "دارای زیره ضد سایش",
        ],
        technical_details: {
          articleNum: "TOPFLEX REBOUND 2403",
          brand: "joma",
          upper_material: "چرم طبیعی",
          outsole: "rebound",
          Collection: "top flex",
          warranty: "گارانتی 150 درصدی اصالت کالا و تعویض سایز",
        },
      },
      {
        id: "12",
        category_id: 2,
        name: "کفش فوتسال جوما تاپ فلکس JOMA TOPFLEX 2476",
        model: "JOMA TOPFLEX 2476",
        brand: "جوما",
        sales: 200,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        color: ["سفید"],
        sizes: ["35", "36", "37", "42.5", "43", "44", "44.5", "45", "46", "47"],
        price: 6220000,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/693897091.PNG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/3551044651.PNG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/2307294642.PNG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/2307294643.PNG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/2307294644.PNG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/5299002385.PNG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس چرم طبیعی",
          "کیفیت دوخت داخلی و بیرونی عالی",
          "کفی ساخته شده از مواد ایوا جهت افزایش نرمی وفیت شوندگی",
          "زیره دارای انعطاف پذیری منحصر به فرد",
          "دارای زیره ضد سایش",
        ],
        technical_details: {
          articleNum: "JOMA TOPFLEX 2476",
          brand: "joma",
          upper_material: "چرم طبیعی",
          Collection: "top flex",
          warranty: "گارانتی 150 درصدی اصالت کالا و تعویض سایز",
        },
      },
      {
        id: "13",
        category_id: 2,
        name: "کفش فوتسال اسیکس مدل ASICS CALCETTO WD8 IC 1113A011",
        model: "ASICS CALCETTO WD8 IC 1113A011",
        brand: "اسیکس",
        sales: 200,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        color: ["سبز"],
        sizes: ["43"],
        price: 8197200,
        discount: {
          type: "dynamic",
          discountedPrice: 7452000,
          startDate: "2025-04-25",
          endDate: "2025-07-1",
        },
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/289582864.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/2594023751.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/5286988252.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/5286988253.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/5286988254.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/7373624215.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/7373624216.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/7373624217.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس چرم مصنوعی",
          "قسمت داخلی و انتهایی کفش کمی پهن است که باعث افزایش راحتی می شود",
          "کیفیت دوخت عالی",
          "وزن مناسب ایده آل",
          "دوام و ماندگاری بالا",
        ],
        technical_details: {
          articleNum: "1113A011",
          brand: "ASICS",
          upper_material: "چرم مصنوعی",
          Collection: "Calcetto",
          quality: "اورجینال(درجه1)",
          warranty: "گارانتی 150 درصدی اصالت کالا و تعویض سایز",
        },
      },
      {
        id: "14",
        category_id: 2,
        name: "کفش فوتسال اسیکس مدل ASICS CALCETTO WD91113A037-001",
        model: "ASICS CALCETTO WD91113A037-001",
        brand: "اسیکس",
        sales: 200,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        color: ["مشکی"],
        sizes: ["37", "39", "40.5", "41", "42", "43", "44", "46"],
        price: 7900000,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/920415156.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/8948062071.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/843856052.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/843856053.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/1908676914.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/1908676915.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/1908676916.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/855768887.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس چرم طبیعی",
          "کیفیت دوخت عالی",
          "قابلیت تهویه هوا مناسب",
          "دوام و ماندگاری منحصر به فرد",
          "انعطاف‌پذیری بالا",
          "افزایش قدرت و دقت ضربات با نوک پا",
        ],
        technical_details: {
          articleNum: "WD91113A037-001",
          brand: "ASICS",
          upper_material: "چرم طبیعی",
          Collection: "Calcetto",
          quality: "اورجینال(درجه1)",
          warranty: "گارانتی 150 درصدی اصالت کالا و تعویض سایز",
        },
      },
      {
        id: "15",
        category_id: 2,
        name: "کفش فوتسال اسیکس مدل ASICS CALLCETO 9 IC 1113A037",
        model: "ASICS CALLCETO 9 IC 1113A037",
        brand: "اسیکس",
        sales: 200,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        color: ["سفید"],
        sizes: ["39", "40", "40.5", "41", "42", "42.5", "43", "44", "46"],
        price: 7900000,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/567728454.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/325862123.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/5261358031.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/325862122.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/9426922734.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/9426922735.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/7473148536.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/7473148537.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/2404790868.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس چرم طبیعی",
          "کیفیت دوخت عالی",
          "وزن سبک",
          "مناسب برای بازیکنان تکنیکی و سرعتی",
          "دوام و ماندگاری منحصر به فرد",
          "زیره با دوام",
        ],
        technical_details: {
          articleNum: "1113A037",
          brand: "ASICS",
          upper_material: "چرم طبیعی",
          Collection: "Calcetto",
          quality: "اورجینال(درجه1)",
          warranty: "گارانتی 150 درصدی اصالت کالا و تعویض سایز",
        },
      },
      {
        id: "16",
        category_id: 2,
        name: "کفش فوتسال اسیکس مدل ASICS CALLCETO 9 IC 1113A037",
        model: "ASICS CALLCETO 9 IC 1113A037",
        brand: "اسیکس",
        sales: 200,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        color: ["قرمز"],
        sizes: ["39", "40", "40.5", "41", "42", "42.5", "43", "44", "46"],
        price: 7900000,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/763717858.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/4087576461.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/4087576462.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/7096185483.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/2114622164.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/2114622165.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس چرم طبیعی",
          "کیفیت دوخت عالی",
          "وزن سبک",
          "مناسب برای بازیکنان تکنیکی و سرعتی",
          "دوام و ماندگاری منحصر به فرد",
          "زیره با دوام",
        ],
        technical_details: {
          articleNum: "1113A037",
          brand: "ASICS",
          upper_material: "چرم طبیعی",
          Collection: "Calcetto",
          quality: "اورجینال(درجه1)",
          warranty: "گارانتی 150 درصدی اصالت کالا و تعویض سایز",
        },
      },
      {
        id: "17",
        category_id: 2,
        name: "کفش فوتسال آدیداس مدل تاپ سالا ADIDAS TOP SALA IC HR0147",
        model: "ADIDAS TOP SALA IC HR0147",
        brand: "آدیداس",
        sales: 200,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        price: null,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/931712196.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/656860422.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/656860421.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/9334375253.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/9334375254.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/7721206095.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس چرم مصنوعی",
          "کیفیت دوخت عالی",
          "قابلیت تهویه هوا مناسب",
          "مناسب برای ضربات با نوک پا",
          "زیره نرم و انعطاف پذیر",
          " مناسب برای چرخش در هنگام ضربات",
        ],
        technical_details: {
          articleNum: "HR0147",
          brand: "adidas",
          upper_material: "چرم مصنوعی",
          Collection: "ADIPRENE",
          quality: "اورجینال(درجه1)",
          warranty: "گارانتی 150 درصدی اصالت کالا و تعویض سایز",
        },
      },
      {
        id: "18",
        category_id: 2,
        name: "کفش فوتسال آدیداس مدل تاپ سالا ADIDAS TOP SALA IC GW1699",
        model: "ADIDAS TOP SALA IC GW1699",
        brand: "آدیداس",
        sales: 200,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        price: null,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/33501159.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/1216697672.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/1216697671.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/1351486233.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/1351486234.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/1351486235.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/6129159896.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس چرم مصنوعی",
          "قدرت تهویه هوای مناسب",
          "وزن سبک",
          "زیره نرم و راحت",
          " مناسب برای چرخش در هنگام ضربات",
          "انعطاف‌پذیری بالا",
        ],
        technical_details: {
          articleNum: "GW1699",
          brand: "adidas",
          upper_material: "چرم مصنوعی",
          Collection: "ADIPRENE",
          quality: "اورجینال(درجه1)",
          warranty: "گارانتی 150 درصدی اصالت کالا و تعویض سایز",
        },
      },
      {
        id: "19",
        category_id: 2,
        name: "کفش فوتسال آدیداس مدل تاپ سالا ADIDAS TOP SALA IC GV7592",
        model: "ADIDAS TOP SALA IC GV7592",
        brand: "آدیداس",
        sales: 200,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        price: null,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/813019091.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/3148539641.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/3910763642.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/3910763643.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/4988632184.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/4988632185.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس چرم مصنوعی",
          "دارای لایه های توری مانند در بخش های کناری جهت افزایش قدرت تهویه هوا در کفش",
          "کیفیت دوخت عالی",
          " مناسب برای چرخش در هنگام ضربات",
          "زیره از جنس لاستیک با فوم",
        ],
        technical_details: {
          articleNum: "Gv7592",
          brand: "adidas",
          upper_material: "چرم مصنوعی",
          Collection: "ADIPRENE",
          quality: "اورجینال(درجه1)",
          warranty: "گارانتی 150 درصدی اصالت کالا و تعویض سایز",
        },
      },
      {
        id: "20",
        category_id: 2,
        name: "کفش فوتسال آدیداس مدل تاپ سالا ADIDAS TOP SALA IC FV 2551",
        model: "ADIDAS TOP SALA IC FV 2551",
        brand: "آدیداس",
        sales: 200,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        price: null,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/289889913.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/6481256921.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/6481256922.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/361918033.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/361918034.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/361918035.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس چرم مصنوعی",
          "قدرت تهویه هوای مناسب",
          "کیفیت دوخت عالی",
          " مناسب برای چرخش در هنگام ضربات",
          "افزایش دقت و سرعت پاس ها و ضربات",
        ],
        technical_details: {
          articleNum: "Fv2551",
          brand: "adidas",
          upper_material: "چرم مصنوعی",
          Collection: "ADIPRENE",
          quality: "اورجینال(درجه1)",
          warranty: "گارانتی 150 درصدی اصالت کالا و تعویض سایز",
        },
      },
      {
        id: "21",
        category_id: 3,
        name: "کفش پیاده روی نایک پگاسوس 38 مدل NIKE AIR ZOOM PEGASUS 38 da6678-001",
        model: "NIKE AIR ZOOM PEGASUS 38 da6678-001",
        brand: "نایک",
        sales: 150,
        ratings: 4.7,
        reviews_count: 25,
        views: 800,
        stock: 10,
        sizes: ["40.5", "41", "42", "45"],
        color: ["مشکی"],
        price: 7850000,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/579516561.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/2093160502.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/5329054031.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/2093160503.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/2093160504.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/6130078175.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس مش مهندسی شده",
          "وزن سبک",
          "انعطاف‌پذیری بالا",
          "قابلیت فیت شوندگی منحصر به فرد",
          "قدرت تهویه هوای مناسب",
          "زیره میانی از جنس فوم جهت نرمی واحساس راحتی",
          "زیره دارای فناوری نایک زوم جهت بازگشت انرژی به پاها و کاهش خستگی پاها",
        ],
        technical_details: {
          articleNum: "Da6698-001",
          brand: "nike",
          upper_material: "مش",
          collection: "pagasus",
          quality: "اورجینال (درجه 1)",
          warranty: "گارانتی 150 درصدی اصالت کالا",
        },
      },
      {
        id: "22",
        category_id: 3,
        name: "کفش پیاده روی نایک پگاسوس 38 مدل NIKE AIR ZOOM PEGASUS 38 IC CW7356-002",
        model: "NIKE AIR ZOOM PEGASUS 38 IC CW7356-002",
        brand: "نایک",
        sales: 200,
        ratings: 4.6,
        reviews_count: 30,
        views: 1000,
        stock: 12,
        sizes: ["40", "40.5"],
        color: ["مشکی"],
        price: 7850000,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/453328282.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/453328282.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/453328282.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/6833354522.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/6833354523.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/4023646714.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/4013660685.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/4013660686.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/6985396377.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس مش",
          "قدرت تهویه هوای مناسب",
          "وزن سبک",
          "فیت شوندگی بالا",
          "زیره دارای فناوری نایک زوم جهت بازگشت انرژی به پاها و کاهش خستگی پاها",
          "زیره میانی از جنس فوم جهت نرمی واحساس راحتی",
        ],
        technical_details: {
          articleNum: "CW7356-002",
          brand: "Nike",
          upper_material: "مش",
          outsole: "air zoom",
          collection: "pagasus",
          quality: "اورجینال (درجه 1)",
          warranty: "گارانتی 150 درصدی اصالت کالا",
        },
      },
      {
        id: "23",
        category_id: 3,
        name: "کفش پیاده روی نایک مدل NIKE REVOLUTION 6 NEXT NATURE MENS IC DC3728-005",
        model: "NIKE REVOLUTION 6 NEXT NATURE MENS IC DC3728-005",
        brand: "نایک",
        sales: 180,
        ratings: 4.5,
        reviews_count: 20,
        views: 900,
        stock: 15,
        sizes: ["40"],
        color: ["مشکی"],
        price: 3850000,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/125892589.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/2987615571.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/5153338662.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/5153338663.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/5153338664.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/8498699125.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس مش و پارچه",
          "قابلیت تهویه هوا ایده آل",
          "زیره دارای فوم جهت نرمی واحساس راحتی",
          "کاهش فشار وارده از زمین به کفش",
          "انعطاف‌پذیری منحصر به فرد",
        ],
        technical_details: {
          articleNum: "DC3728-005",
          brand: "nike",
          upper_material: "مش",
          collection: "Revolution",
          quality: "اورجینال (درجه 1)",
          warranty: "گارانتی 150 درصدی اصالت کالا",
        },
      },
      {
        id: "24",
        category_id: 3,
        name: "کفش پیاده روی نایک مدل NIKE WINFLO 8 CW3419-006",
        model: "NIKE WINFLO 8 CW3419-006",
        brand: "نایک",
        sales: 220,
        ratings: 4.6,
        reviews_count: 25,
        views: 1100,
        stock: 14,
        sizes: ["39", "41", "42.5", "43"],
        color: ["مشکی"],
        price: 7450000,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/108417251.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/8268068191.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/1170702792.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/3182457233.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/3182457234.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/6631513325.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/7671373676.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/4243072477.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/6329708438.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس مش",
          "قدرت تهویه بالا",
          "وزن سبک",
          "زیره دارای فناوری نایک زوم جهت افزایش سرعت و چابکی و پویایی حرکت",
          "زیره دارای فوم جهت نرمی",
        ],
        technical_details: {
          articleNum: "CW3419-006",
          brand: "nike",
          upper_material: "مش",
          outsole: "air zoom",
          collection: "Winflo",
          quality: "اورجینال (درجه 1)",
          warranty: "گارانتی 150 درصدی اصالت کالا",
        },
      },
      {
        id: "25",
        category_id: 3,
        name: "کفش پیاده روی جوما مدل JOMA ZINC 2101",
        model: "JOMA ZINC 2101",
        brand: "جوما",
        sales: 150,
        ratings: 4.7,
        reviews_count: 18,
        views: 800,
        stock: 12,
        price: null,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/49471242.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/221281692.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/1153240791.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/221281693.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/302295634.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس نایلون",
          "زیره از جنس لاستیک",
          "زیره دارای فوم جهت نرمی واحساس راحتی",
          "دارای وزن سبک",
          "انعطاف پذیری بالا",
        ],
        technical_details: {
          articleNum: "JOMA ZINC 2101",
          brand: "joma",
          upper_material: "کتان",
          collection: "Zinc",
          quality: "اورجینال (درجه 1)",
          warranty: "گارانتی 150 درصدی اصالت کالا",
        },
      },
      {
        id: "26",
        category_id: 3,
        name: "کفش پیاده روی جوما مدل MAGNESIO LADY 2101 BLACK WHITE",
        model: "MAGNESIO LADY 2101 BLACK WHITE",
        brand: "جوما",
        sales: 150,
        ratings: 4.7,
        reviews_count: 18,
        views: 800,
        stock: 12,
        price: null,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/781346878.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/781346878.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/5923367281.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/7474702602.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس TPU",
          "دارای وزن سبک",
          "انعطاف پذیری بالا",
          "زیره از جنس لاستیک و EVA جهت افزایش نرمی و انعطاف پذیری",
        ],
        technical_details: {
          articleNum: "MAGNESIO LADY 2101 BLACK WHITE",
          brand: "joma",
          upper_material: "TPU",
          quality: "اورجینال (درجه 1)",
          warranty: "گارانتی 150 درصدی اصالت کالا",
        },
      },
      {
        id: "27",
        category_id: 3,
        name: "کفش پیاده روی جوما مدل JOMA LINX MEN 2101 BLACK",
        model: "JOMA LINX MEN 2101 BLACK",
        brand: "جوما",
        sales: 150,
        ratings: 4.7,
        reviews_count: 18,
        views: 800,
        stock: 12,
        price: null,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/825234282.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/6323617072.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/9353333001.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/6323617073.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/9016581574.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/9016581575.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس نایلون مهندسی شده و TPU",
          "زیره دارای خاصیت EVA",
          "زیره از جنس لاستیک ضد سایش",
          "انعطاف‌پذیری بالا",
          "دارای وزن سبک",
        ],
        technical_details: {
          articleNum: "JOMA LINX MEN 2101 BLACK",
          brand: "joma",
          upper_material: "TPU",
          quality: "اورجینال (درجه 1)",
          warranty: "گارانتی 150 درصدی اصالت کالا",
        },
      },
      {
        id: "28",
        category_id: 3,
        name: "کفش پیاده روی جوما مدل JOMA LINX MEN 2103 NEW",
        model: "JOMA LINX MEN 2103 NEW",
        brand: "جوما",
        sales: 150,
        ratings: 4.7,
        reviews_count: 18,
        views: 800,
        stock: 12,
        price: null,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/44128766.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/4139078032.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/104448291.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/9070720343.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/9070720344.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/9359477565.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس نایلون مهندسی شده و TPU",
          "زیره از جنس لاستیک ضد سایش",
          "وزن سبک و حدود 230 گرم",
          "کفی میانی از فایلون جهت افزایش بازدهی حرکت",
          "مناسب برای افراد با وزن متعادل",
        ],
        technical_details: {
          articleNum: "JOMA LINX MEN 2103 NEW",
          brand: "joma",
          upper_material: "TPU",
          quality: "اورجینال (درجه 1)",
          warranty: "گارانتی 150 درصدی اصالت کالا",
        },
      },
      {
        id: "29",
        category_id: 3,
        name: "کفش پیاده روی نیوبالانس مدل NEW BALANCE RUNNING FRESH FOAM TEMPO VISION BLUE",
        model: "NEW BALANCE RUNNING FRESH FOAM TEMPO VISION BLUE",
        brand: "نیوبالانس",
        sales: 150,
        ratings: 4.7,
        reviews_count: 18,
        views: 800,
        stock: 12,
        price: null,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/134073016.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/6897793161.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/4495512682.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/4495512683.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/33483564.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس مش",
          "دارای وزن سبک و ایده آل",
          "زیره نرم و با دوام",
          "تهویه هوا عالی",
          "دارای انعطاف پذیری بالا",
        ],
        technical_details: {
          articleNum: "JOMA LINX MEN 2103 NEW",
          brand: "New Balance",
          upper_material: "مش",
          quality: "اورجینال (درجه 1)",
          warranty: "گارانتی 150 درصدی اصالت کالا",
        },
      },
      {
        id: "30",
        category_id: 3,
        name: "کفش پیاده روی نیوبالانس مدل NEW BALANCE 997 BLACK CM997HTK",
        model: "NEW BALANCE 997 BLACK CM997HTK",
        brand: "نیوبالانس",
        sales: 150,
        ratings: 4.7,
        reviews_count: 18,
        views: 800,
        stock: 12,
        price: null,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/876582421.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/3512669021.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/3377880462.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/3377880463.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/2188257074.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/2188257075.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس مش",
          "دارای وزن سبک و ایده آل",
          "زیره نرم و با دوام",
          "تهویه هوا عالی",
          "دارای انعطاف پذیری بالا",
        ],
        technical_details: {
          articleNum: "CM997HTK",
          brand: "New Balance",
          upper_material: "الیاف مصنوعی",
          quality: "اورجینال (درجه 1)",
          warranty: "گارانتی 150 درصدی اصالت کالا",
        },
      },
      {
        id: "31",
        category_id: 4,
        name: "کفش چمن مصنوعی نایک تمپو لجند 9 آکادمی NIKE TIEMPO LEGEND 9 ACADEMY TF IC DA1191-075",
        model: "NIKE TIEMPO LEGEND 9 ACADEMY TF IC DA1191-075",
        brand: "نایک",
        sales: 200,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        color: ["چند رنگ"],
        sizes: ["40", "40.5", "42", "43"],
        price: 5850000,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/43350769.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/5906143101.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/7274695652.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/7274695653.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/7274695654.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/9041833475.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس چرم طبیعی گوساله",
          "دارای چرم جیر در قسمت جلویی کفش جهت دوام این ناحیه",
          "وزن سبک نسبت به سری های قبلی",
          "راحتی و انعطاف پذیری زیاد",
        ],
        technical_details: {
          articleNum: "DA1191-075",
          brand: "nike",
          upper_material: "چرم طبیعی",
          Collection: "tiempo",
          quality: "اورجینال(درجه1)",
          warranty: "گارانتی 150 درصدی اصالت کالا و تعویض سایز",
        },
      },
      {
        id: "32",
        category_id: 4,
        name: "کفش چمن مصنوعی نایک تمپو لجند 9 آکادمی NIKE TIEMPO LEGEND 8 ACADEMY TF IC At6100-090",
        model: "NIKE TIEMPO LEGEND 8 ACADEMY TF IC At6100-090",
        brand: "نایک",
        sales: 200,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        price: null,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/954299655.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/9689345941.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/5015367922.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/5015367923.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/5015367924.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/4468946415.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "رویه از جنس چرم طبیعی گوساله",
          "رویه عایق حرارتی و رطوبتی",
          "سازگاری با فرم های مختلف پا",
          "وزن متعادل",
          "توانایی کنترل بالای توپ",
          "زیره دارای خاصیت آنتی شوک",
        ],
        technical_details: {
          articleNum: "At6100-090",
          brand: "nike",
          upper_material: "چرم طبیعی",
          Collection: "tiempo",
          quality: "اورجینال(درجه1)",
          warranty: "گارانتی 150 درصدی اصالت کالا و تعویض سایز",
        },
      },
      {
        id: "33",
        category_id: 8,
        name: "قلم بند آمبرو UMBRO NEO MINUMUS SHINGUARDS 21035U-HMM",
        model: "UMBRO NEO MINUMUS SHINGUARDS 21035U-HMM",
        brand: "آمبرو",
        sales: 200,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        price: null,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/745135644.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/4983263021.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "جنس ترکیبی از پلاستیک، پلی استر، مواد EVA",
          "دوام و ماندگاری بالا",
          "مقام نسبت به ضربه",
          "دارای چاپ گرافیکی",
        ],
        technical_details: {
          brand: "umbro",
          articleNum: "21035U-HMM",
        },
      },
      {
        id: "34",
        category_id: 8,
        name: "قلم بند آمبرو UMBRO NEO MINUMUS SHINGUARDS 21035U-HMM",
        model: "UMBRO NEO MINUMUS SHINGUARDS 21035U-HMM",
        brand: "آمبرو",
        sales: 200,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        price: null,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/896569294.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/8460123861.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "جنس ترکیبی از پلاستیک، پلی استر، مواد EVA",
          "دوام و ماندگاری بالا",
          "مقام نسبت به ضربه",
          "دارای چاپ گرافیکی",
        ],
        technical_details: {
          brand: "umbro",
          articleNum: "21035U-HMM",
        },
      },
      {
        id: "35",
        category_id: 8,
        name: " زانوبند دروازه بانی اسیکس مدل ASICS BASICS KNEEPAD-146814 ",
        model: "ASICS BASICS KNEEPAD-146814",
        brand: "اسیکس",
        sales: 200,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        price: null,
        discount: null,
        image:
          "https://www.orglandsports.com/WebsiteImages/ProductImages/81204312.JPG",
        images: [
          "https://www.orglandsports.com/WebsiteImages/ProductImages/4738771621.JPG",
          "https://www.orglandsports.com/WebsiteImages/ProductImages/4738771622.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "دارای پدهای محافظ ژله ای",
          "نرم و منعطف",
          "دارای خاصیت کشسانی ایده آل",
          "توانایی محافظت کامل از قسمت آرنج",
        ],
        technical_details: {
          articleNum: "KNEEPAD-146814",
          brand: "asics",
        },
      },
      {
        id: "37",
        category_id: 10,
        name: "توپ فوتسال اورجینال الشپرت مدل medusa",
        model: "uhlsport medusa futsal ball100161302",
        brand: "الشپرت",
        sales: 200,
        ratings: 4.5,
        reviews_count: 20,
        views: 1000,
        stock: 10,
        price: 5500000,
        discount: null,
        color: ["سفید"],
        sizes: [4],
        image:
          "https://www.orglandsportt.com/WebsiteImages/ProductImages/893203138.JPG",
        images: [
          "https://www.orglandsportt.com/WebsiteImages/ProductImages/9141640881.JPG",
          "https://www.orglandsportt.com/WebsiteImages/ProductImages/73600002.JPG",
          "https://www.orglandsportt.com/WebsiteImages/ProductImages/8231580643.JPG",
          "https://www.orglandsportt.com/WebsiteImages/ProductImages/5783232754.JPG",
          "https://www.orglandsportt.com/WebsiteImages/ProductImages/5783232755.JPG",
        ],
        key_features: [
          "دارای ضمانت اصالت کالا",
          "مورد تایید فیفا",
          "سایز 4",
          "ساخت پاکستان",
          "2 ماه وارانتی تعویض",
          "سال ساخت 2024",
        ],
        technical_details: {
          articleNum: "ball100161302",
          brand: "uhlsport",
        },
      },
    ];
    if (id) {
      const product = products.find((p) => p.id == id);
      if (product) {
        res.status(200).json(product);
      } else {
        res.status(404).json({ message: "product not found" });
      }
    } else if (category) {
      const product = products.filter((p) => p.category_id == category);
      if (product) {
        res.status(200).json(product);
      } else {
        res.status(404).json({ message: "product not found" });
      }
    } else if (brand) {
      const product = products.filter(
        (p) => p.brand == brand
      );
      if (product) {
        res.status(200).json(product);
      } else {
        res.status(404).json({ message: "product not found" });
      }
    } else {
      res.status(200).json(products);
    }
  } else {
    res.setHeader("Allow", ["GET", "POST"]);
    res.status(405).end(`Method ${req.method} Not Allowed`);
  }
}
